### ISSUE TITLE
蓝柠萌

### ISSUE THREAD

**Issue by mkpoli** [LambdaInnovation/Feedback#8]
<sistersicing@outlook.com>

> 使用的时候发现了两个关于技能的bug。
> 使用【危险传送】和【采集光束】这两个技能的时候会崩出游戏。
> 不是结束游戏，提示失去连接弹出至主菜单。
> 使用的Minecraft为多mod整合。
> JAVA版本：X64_1.8.0_91
> Minecraft forge： Forge10.13.4.1614-1.7.10

（邮件含附件）
Attaching files INCLUDED

**Comment by nirvanaxiao6** [comment]
已回复
可关闭
